// Copies the single-file Vite build into the Rust crate as src/dashboard.html,
// where traza-server embeds it via include_str!. Run through `npm run build`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const built = join(here, '..', 'dist', 'index.html');
const target = join(here, '..', '..', 'src', 'dashboard.html');

let html = readFileSync(built, 'utf8');
if (!/^<!doctype html>/i.test(html)) {
  throw new Error('built page does not start with <!doctype html>');
}
if (!html.includes('<title>Traza</title>')) {
  throw new Error('built page lost its <title>Traza</title>');
}
// Provenance note for readers of the generated file (after the doctype so
// the served document still starts with it).
html = html.replace(
  /^<!doctype html>/i,
  '<!doctype html>\n<!-- Generated by ui/ (npm run build). Do not edit by hand; edit ui/src and rebuild. -->'
);
writeFileSync(target, html);
console.log('embedded ' + built + ' -> ' + target + ' (' + html.length + ' bytes)');
